version: '3.8'
services:
 
  # Prometheus — собирает метрики
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus  # ← монтируем ПАПКУ, а не файл
  # Grafana — визуализация
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # Blackbox Exporter — проверяет доступность HTTP
  blackbox:
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    ports:
      - "9115:9115"