global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'website'
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [http://localhost]
    static_configs:
      - targets: ['localhost:9115']