---
- name: Setup Docker, Docker Compose and Monitoring 
  hosts: all
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    - name: Install aptitud
      apt:
        name: aptitude
        state: latest
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install ufw (firewall)
      apt:
        name: ufw
        state: present

    - name: Allow SSH, HTTP, Grafana
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22   # SSh
        - 80   # Сайт
        - 3000 # Grafana