---
- name: Setup Docker, Docker Compose and Monitoring on Ubuntu EC2
  hosts: all
  become: yes
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Install ufw (firewall)
      apt:
        name: ufw
        state: present

    - name: Allow SSH, HTTP, Grafana
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22   # SSH
        - 80   # Сайт
        - 3000 # Grafana