---
- name: Setup Docker, Docker Compose and Monitoring 
  hosts: all
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    - name: Install aptitud
      apt:
        name: aptitude
        state: latest
        update_cache: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install required system packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
 
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'


    - name: Install ufw (firewall)
      apt:
        name: ufw
        state: present

    - name: Create app directory
      file:
        path: /opt/monitoring
        state: directory

    - name: Copy website files
      copy:
        src: ../../site/
        dest: /opt/monitoring/site/

    - name: Copy docker-compose.yml
      template:
        src: files/docker-compose.yml.j2
        dest: /opt/monitoring/docker-compose.yml

    - name: Start monitoring stack
      shell: docker-compose up -d
      args:
        chdir: /opt/monitoring

    - name: Allow SSH, HTTP, Grafana
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22   # SSh
        - 80   # Сайт
        - 3000 
        - 9090 # Grafana